/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
'use client'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function HatModel(props) {
  const { nodes, materials } = useGLTF('/models/strawhatsnow-transformed.glb');

  const modelRef = useRef();
  useFrame((()=> {
    modelRef.current.rotation.y += 0.004
  }))
  return (
    <group {...props} dispose={null}
    ref={modelRef}
    scale={[0.22,0.22,0.22]}
    rotation={[0.5, -1, 0]}
    position={[1,-1.1,0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials['straw.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.fabric}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_12.geometry}
        material={materials.paper}
      />
    </group>
  )
}

useGLTF.preload('/models/strawhatsnow-transformed.glb')