/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: keiichiisozaki (https://sketchfab.com/keiichiisozaki)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/original-anime-girls-1b7084a8d4e04620879610059d98951c
Title: Original Anime Girls
*/
"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';


export default function Staff(props) {
  const { nodes, materials } = useGLTF('/models/maid-transformed.glb')
  const modelRef = useRef();

  useFrame((state) => {
    modelRef.current.position.y =
      -0.5 + Math.sin(state.clock.elapsedTime) * 0.15;
  });

  return (
    <group {...props} dispose={null}
        ref={modelRef}
        position={[1.1,-1, 0.1]}
        scale={[0.22, 0.22, 0.22]}
        >
      <mesh
        name="girl_skin2"
        castShadow
        receiveShadow
        geometry={nodes.girl_skin2.geometry}
        material={materials.mtl_skin2}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={10.208}
      />
      <mesh
        name="girl_face2"
        castShadow
        receiveShadow
        geometry={nodes.girl_face2.geometry}
        material={materials.mtl_face2}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="girl_cloth2"
        castShadow
        receiveShadow
        geometry={nodes.girl_cloth2.geometry}
        material={materials.mtl_cloth2}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="girl_hair"
        castShadow
        receiveShadow
        geometry={nodes.girl_hair.geometry}
        material={materials.mtl_hair}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="eyelash003"
        castShadow
        receiveShadow
        geometry={nodes.eyelash003.geometry}
        material={materials.white}
        position={[0, 0.748, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="girl_skin"
        castShadow
        receiveShadow
        geometry={nodes.girl_skin.geometry}
        material={materials.mtl_skin}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="girl_cloth"
        castShadow
        receiveShadow
        geometry={nodes.girl_cloth.geometry}
        material={materials.mtl_cloth}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="girl_face"
        castShadow
        receiveShadow
        geometry={nodes.girl_face.geometry}
        material={materials.mtl_face}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="pants2"
        castShadow
        receiveShadow
        geometry={nodes.pants2.geometry}
        material={materials.Root}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="girl_hair2"
        castShadow
        receiveShadow
        geometry={nodes.girl_hair2.geometry}
        material={materials.mtl_hair2}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/models/maid-transformed.glb')
